# Generated by Django 5.0.2 on 2024-02-24 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Continent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_continent', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_pays', models.CharField(max_length=50)),
                ('space', models.FloatField()),
                ('population', models.IntegerField()),
                ('device', models.FloatField()),
                ('code', models.CharField(max_length=5)),
                ('Continent', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='pays', to='lespays.continent')),
            ],
        ),
    ]
