# Generated by Django 5.0.2 on 2024-02-24 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lespays', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pays',
            name='device',
            field=models.CharField(max_length=50),
        ),
    ]
